import React from "react";

const BodyRP = () => {
    return (
        <div id="main">
            <div className="inner">
            
                <a href="" className="logo">
                 <span className="symbol"></span><span className="title">
                 <h1> Rosa Parks</h1></span>
                  </a>
                <span className="image left"><img src="images/rpchildhood.jpg" alt=""/></span>
                <p align="left">Rosa Louise Parks was nationally recognized as the “mother of the modern day civil rights movement” in America. Her refusal to surrender her seat to a white male passenger on a Montgomery, Alabama bus, December 1, 1955, triggered a wave of protest December 5, 1955 that reverberated throughout the United States. Her quiet courageous act changed America, its view of black people and redirected the course of history.</p>
                <p align="left">Mrs. Parks was born Rosa Louise McCauley, February 4, 1913 in Tuskegee, Alabama. She was the first child of James and Leona Edwards McCauley. Her brother, Sylvester McCauley, now deceased, was born August 20, 1915. Later, the family moved to Pine Level, Alabama where Rosa was reared and educated in the rural school. When she completed her education in Pine Level at age eleven, her mother, Leona, enrolled her in Montgomery Industrial School for Girls (Miss White’s School for Girls), a private institution. After finishing Miss White’s School, she went on to Alabama State Teacher’s College High School. She, however, was unable to graduate with her class, because of the illness of her grandmother Rose Edwards and later her death.</p>
                <p align="left">As Rosa Parks prepared to return to Alabama State Teacher’s College, her mother also became ill, therefore, she continued to take care of their home and care for her mother while her brother, Sylvester, worked outside of the home. She received her high school diploma in 1934, after her marriage to Raymond Parks, December 18, 1932. Raymond, now deceased was born in Wedowee, Alabama, Randolph County, February 12, 1903, received little formal education due to racial segregation. He was a self-educated person with the assistance of his mother, Geri Parks. His immaculate dress and his thorough knowledge of domestic affairs and current events made most think he was college educated. He supported and encouraged Rosa’s desire to complete her formal education.</p>
                <span className="image main"><img src="images/rpmug.jpg" alt="" /></span>
                <p align="left">Mr. Parks was an early activist in the effort to free the “Scottsboro Boys,” a celebrated case in the 1930′s. Together, Raymond and Rosa worked in the National Association for the Advancement of Colored People (NAACP’s) programs. He was an active member and she served as secretary and later youth leader of the local branch. At the time of her arrest, she was preparing for a major youth conference.</p>
                <span className="image left"><img src="images/rpbusboycott.jpg" alt="" /></span>
                <p align="left">After the arrest of Rosa Parks, black people of Montgomery and sympathizers of other races organized and promoted a boycott of the city bus line that lasted 381 days. Dr. Martin Luther King, Jr. was appointed the spokesperson for the Bus Boycott and taught nonviolence to all participants. Contingent with the protest in Montgomery, others took shape throughout the south and the country. They took form as sit-ins, eat-ins, swim-ins, and similar causes. Thousands of courageous people joined the “protest” to demand equal rights for all people.</p>
                <p align="left">Congressman John Conyers First Congressional District of Michigan employed Mrs. Parks, from 1965 to 1988. In February, 1987, she co-founded the Rosa and Raymond Parks Institute for Self Development with Ms. Elaine Eason Steele in honor of her husband, Raymond (1903-1977). The purpose is to motivate and direct youth not targeted by other programs to achieve their highest potential. Rosa Parks sees the energy of young people as a real force for change. It is among her most treasured themes of human priorities as she speaks to young people of all ages at schools, colleges, and national organizations around the world.</p>
                <span className="image main"><img src="images/rosa-parks5.jpg" alt="" /></span>
                <p align="left">The Rosa and Raymond Parks Institute for Self Development’s “Pathways to Freedom program, traces the underground railroad into the civil rights movement and beyond. Youth, ages 11 through 17, meet and talk with Mrs. Parks and other national leaders as they participate in educational and historical research throughout the world. They journey primarily by bus as “freedom riders” did in the 1960′s,the theme: “Where have we been? Where are we going?”</p>
                <p align="left">As a role model for youth she was stimulated by their enthusiasm to learn as much about her life as possible. A modest person, she always encourages them to research the lives of other contributors to world peace. The Institute and The Rosa Parks Legacy are her legacies to people of good will.</p>
                <h2>I would like to be remembered as a person who wanted to be free... so other people would be also free.</h2>
                <p align="left">Mrs. Parks received more than forty-three honorary doctorate degrees, including one from SOKA UNIVERSITY, Tokyo Japan, hundreds of plaques, certificates, citations, awards and keys to many cities. Among them are the NAACP’s Spingarn Medal, the UAW’s Social Justice Award, the Martin Luther King, Jr. Non – Violent Peace Prize and the ROSA PARKS PEACE PRIZE in 1994, Stockholm Sweden, to name a few. In September 1996 President William J. Clinton, the forty second President of the United States of America gave Mrs. Parks the MEDAL OF FREEDOM, the highest award given to a civilian citizen.
                Published Act no.28 of 1997 designated the first Monday following February 4, as Mrs Rosa Parks’ Day in the state of Michigan, her home state. She is the first living person to be honored with a holiday.</p>
                <p align="left">She was voted by Time Magazine as one of the 100 most Influential people of the 20th century. A Museum and Library is being built in her honor, in Montgomery, AL and will open in the fall of the year 2000 (ground breaking April 21, 1998). On September 2, 1998 The Rosa L. Parks Learning Center was dedicated at Botsford Commons, a senior community in Michigan. Through the use of computer technology, youth will mentor seniors on the use of computers. (Mrs. Parks was a member of the first graduating class on November 24, 1998). On September 26, 1998 Mrs. Parks was the recipient of the first International Freedom Conductor’s Award by the National Underground Railroad Freedom Center in Cincinnati, Ohio.</p>

                 </div>
        </div>
    );
}

export default BodyRP;